---
name: Heal_and_Feed
version: 0.0.1
main: CapitaineVole\Heal_and_Feed\Main
api: 3.0.0
author: CapitaineVole

commands:
  heal:
    description: "Permet de vous heal"
    aliases: ['health']
  feed:
    description: "Permet de vous feed"
    aliases: ['food']

permissions:
  use.heal:
    description: "Perm pour heal"
    default: op
  use.feed:
    description: "Perm pour feed"
    default: op
...
